name: "godot-tester"
description: "Runs all GUT tests you have for your Godot game"
inputs:
  version:
    description: "Your Godot version number e.g. 3.2.2"
    required: true
    default: "3.2.2"
  release_type:
    description: "Your Godot release type e.g. rc2, beta3"
    required: false
    default: "stable"
  path:
    description: "Give relative path to your project.godot, if not in top level of repo"
    required: false
    default: "./"
  is-mono:
    description: "Test against mono version? Default: false"
    required: false
    default: "false"
  import-time:
    description: "How long to spend on importing assets, don't set if testing is not required"
    required: false
    default: "1"
  test-timeout:
    description: "How long the test should be run before it's timed out and fails"
    required: false
    default: "300"
  minimum-pass:
    description: "Decimal value for minimum passing score e.g. if 88% of tests pass and minimum-pass is 0.8, then action passes."
    required: false
    default: "0.99"
  test-dir:
    description: "Directory containing Gut tests"
    required: false
    default: "res://test"
  direct-scene:
    description: "If instead of running the GUT command line you'd like to run a GUT scene instead: recommended to extend gut's plugin script and exit godot when all tests complete"
    required: false
    default: "false"
  assert-check:
    description: "Set to true to check by assert count instead of tests"
    required: false
    default: "false"
  max-fails:
    description: "Maximum number of failing asserts or tests, if this or pass rate fails then the action will fail. Is not checked if you do not set it"
    required: false
    default: "false"

build:
  using: 'docker'
  image: 'Dockerfile'
  args:
    VERSION: $${{ secrets.TEST_SECRET }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.version }}
  - ${{ inputs.release_type }}
  - ${{ inputs.path }}
  - ${{ inputs.is-mono }}
  - ${{ inputs.import-time }}
  - ${{ inputs.test-timeout }}
  - ${{ inputs.minimum-pass }}
  - ${{ inputs.test-dir }}
  - ${{ inputs.direct-scene }}
  - ${{ inputs.assert-check }}
  - ${{ inputs.max-fails }}

branding:
  icon: 'chevron-right'
  color: 'green'
